### ISSUE TITLE
Installation fails: No such file or directory: 'readme.md'

### ISSUE THREAD

**Issue by tripleee** [ghasedakapi/ghasedak-python#5]
The `setup.py` script probably needs a tweak.

```
(new-venv) tripleee$ pip install ghasedak
Collecting ghasedak
  Downloading https://files.pythonhosted.org/packages/84/47/6dc68b46ab345ecb5fefee2870a91879dc78e8008de4027059d356ecaa5e/ghasedak-0.1.8.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /private/tmp/new-venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/r3/y4rx1vtj3kz0ybshqbm9ypsx0grl3m/T/pip-install-a2x65nwc/ghasedak/setup.py'"'"'; __file__='"'"'/private/var/folders/r3/y4rx1vtj3kz0ybshqbm9ypsx0grl3m/T/pip-install-a2x65nwc/ghasedak/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/r3/y4rx1vtj3kz0ybshqbm9ypsx0grl3m/T/pip-install-a2x65nwc/ghasedak/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r3/y4rx1vtj3kz0ybshqbm9ypsx0grl3m/T/pip-install-a2x65nwc/ghasedak/setup.py", line 3, in <module>
        with open("readme.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

See also https://stackoverflow.com/questions/68752013/filenotfounderror-errno-2-no-such-file-or-directory-readme-md

Python 3.8.2 installed via `pyenv` on MacOS Big Sur

**Comment by hamidrajabi** [comment]
Is your 'pip' upgraded (pip install --upgrade pip)?

**Comment by tripleee** [comment]
Sorry for dropping the ball on this. Indeed, upgrading `pip` resolves it for me.
